language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

install:
  - yarn
  - yarn global add codecov

script:
  - yarn test
  - yarn run build


after_script:
  - codecov

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local_dir: dist
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages
